---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Post
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: content/blog/images
public_path: "./images"
front_matter_path: "./images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_docker_image: node:10
  install_dependencies_command: npm install
  instant_preview_command: npm start
  mount_path: "/srv"
  working_dir: "/srv/src"
  preview_output_directory: "src/dist"
  preview_env:
  - ENV=staging
