locale: 'ru'

backend:
  name: github
  repo: dikfer/my-blog
  
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "static/uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image_caption", name: "image_caption", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}  
  - name: "post_video"
    label: "Post_video"
    folder: "static/uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image_caption", name: "image_caption", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Video", name: "video", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}